# Generated by Django 5.2 on 2025-04-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='userImage',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
